create table battle_participant
(
    id                   bigint  not null
        primary key,
    initiative_roll       integer not null,
    max_hit_points       integer not null,
    current_hit_points   integer not null,
    temporary_hit_points integer not null,
    strength             integer not null,
    dexterity            integer not null,
    endurance            integer not null,
    intelligence         integer not null,
    wisdom               integer not null,
    charisma             integer not null,
    acrobatics           integer not null,
    animal_handing       integer not null,
    arcana               integer not null,
    athletic             integer not null,
    deceptions           integer not null,
    history              integer not null,
    insight              integer not null,
    intimidation         integer not null,
    investigation        integer not null,
    medicine             integer not null,
    nature               integer not null,
    perception           integer not null,
    performance          integer not null,
    persuasion           integer not null,
    religion             integer not null,
    sleight_of_hand      integer not null,
    stealth              integer not null,
    survival             integer not null,
    character_id         bigint,
    FOREIGN KEY (character_id) REFERENCES character (id),
    armor_class          integer not null,
    death_saves          integer not null,
    hit_dice             integer not null,
    initiative     integer not null,
    inspiration          integer not null,
    proficiency_bonus    integer not null,
    speed                integer not null,
    bonds                varchar(255),
    flaws                varchar(255),
    ideals               varchar(255),
    personality_traits   varchar(255),
    character_name       varchar(255),
    player_name          varchar(255),
    lvl                  integer not null,
    clazz_id             bigint,
    FOREIGN KEY (clazz_id) REFERENCES clazz (id),
    race_id              bigint,
    FOREIGN KEY (race_id) REFERENCES race (id),
    background           varchar(255),
    experience_points    integer not null
);