package com.example.demo1.entity.character.clazz;

public enum Saves {
    STRENGTH_AND_CONSTITUTION,
    DEXTERITY_AND_CHARISMA,
    WISDOM_AND_CHARISMA,
    INTELLIGENCE_AND_WISDOM,
    STRENGTH_OR_DEXTERITY,
    STRENGTH_AND_DEXTERITY,
    DEXTERITY_AND_WISDOM,
    DEXTERITY_INTELLIGENCE,
    CONSTITUTION_AND_CHARISMA,
    CONSTITUTION_AND_INTELLIGENCE,

}
