spring:
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/dnd
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    change-log: classpath:/liquibase/changelog-master.yaml
